In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
print(data.columns.tolist())

['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited']

In [4]:
### Preprocess the data
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
## Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [6]:
## One hot encode 'Geography'
onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
## Combine one-hot encoded columns with original data
data=pd.concat(
    [data.drop('Geography',axis=1).reset_index(drop=True),
    geo_encoded_df.reset_index(drop=True)],
    axis=1
)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [10]:
## Split the data into features and target
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [11]:
## Split  the data in training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

ANN Regression Problem statement

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [17]:
## Build the model
model=Sequential([
    Dense(64, activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1) # Output layer for regression

])

## complile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [19]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

#Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [21]:
## Set up Early stopping
early_stopping_callback= EarlyStopping(monitor='val_loss',patience=10, restore_best_weights=True)

In [22]:
## Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From d:\ANN\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\ANN\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 3ms/step - loss: 100382.2812 - mae: 100382.2812 - val_loss: 98531.7812 - val_mae: 98531.7812
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 99686.2188 - mae: 99686.2188 - val_loss: 97124.7266 - val_mae: 97124.7266
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 97240.9922 - mae: 97240.9922 - val_loss: 93517.4141 - val_mae: 93517.4141
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 92409.9609 - mae: 92409.9609 - val_loss: 87458.8828 - val_mae: 87458.8828
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 85290.0469 - mae: 85290.0469 - val_loss: 79544.8281 - val_mae: 79544.8281
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 76775.7109 - mae: 76775.7109 - val_loss: 71019.9922 - val_mae: 71019.9922
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 68264.7969 - mae: 68264.7969 - val_loss: 63420.7109 - val_mae: 63420.7109
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 61124.4258 - mae: 61124.4258 - val_loss: 57551.2695 - val_mae: 57551.2695
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 56114.0859 - mae: 56114.0859 - val_loss: 53866.6406 - val_mae: 53866.6406
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 53180.6328 - mae: 53180.6328 - val_loss: 52029.1758 - val_mae: 52029.1758
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 51687.3164 - mae: 51687.3164 - val_loss: 51261.0195 - val_mae: 51261.0195
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 50981.5547 - mae: 50981.5547 - val_loss: 50935.5547 - val_mae: 50935.5547
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 50635.0195 - mae: 50635.0195 - val_loss: 50807.1953 - val_mae: 50807.1953
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 50461.5977 - mae: 50461.5977 - val_loss: 50725.0000 - val_mae: 50725.0000
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 50350.4414 - mae: 50350.4414 - val_loss: 50671.9453 - val_mae: 50671.9453
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 50276.4961 - mae: 50276.4961 - val_loss: 50620.2930 - val_mae: 50620.2930
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 50211.9922 - mae: 50211.9922 - val_loss: 50581.4688 - val_mae: 50581.4688
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 50156.1172 - mae: 50156.1172 - val_loss: 50556.7812 - val_mae: 50556.7812
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 50106.4141 - mae: 50106.4141 - val_loss: 50525.9453 - val_mae: 50525.9453
Epoch 20/100
250/250 [==============================] - 0s 2ms/step - loss: 50062.8555 - mae: 50062.8555 - val_loss: 50494.2227 - val_mae: 50494.2227
Epoch 21/100
250/250 [==============================] - 0s 2ms/step - loss: 50026.5312 - mae: 50026.5312 - val_loss: 50467.3828 - val_mae: 50467.3828
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 49992.0078 - mae: 49992.0078 - val_loss: 50449.7383 - val_mae: 50449.7383
Epoch 23/100
250/250 [==============================] - 0s 2ms/step - loss: 49958.4258 - mae: 49958.4258 - val_loss: 50427.2539 - val_mae: 50427.2539
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 49929.7578 - mae: 49929.7578 - val_loss: 50411.8555 - val_mae: 50411.8555
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 49903.0703 - mae: 49903.0703 - val_loss: 50394.4023 - val_mae: 50394.4023
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 49877.0664 - mae: 49877.0664 - val_loss: 50382.5625 - val_mae: 50382.5625
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 49858.4570 - mae: 49858.4570 - val_loss: 50366.7305 - val_mae: 50366.7305
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 49837.6914 - mae: 49837.6914 - val_loss: 50354.4805 - val_mae: 50354.4805
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 49817.0156 - mae: 49817.0156 - val_loss: 50342.0586 - val_mae: 50342.0586
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 49798.1094 - mae: 49798.1094 - val_loss: 50328.1602 - val_mae: 50328.1602
Epoch 31/100
250/250 [==============================] - 0s 2ms/step - loss: 49781.9570 - mae: 49781.9570 - val_loss: 50322.3594 - val_mae: 50322.3594
Epoch 32/100
250/250 [==============================] - 0s 2ms/step - loss: 49767.6250 - mae: 49767.6250 - val_loss: 50312.8906 - val_mae: 50312.8906
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 49750.1680 - mae: 49750.1680 - val_loss: 50302.1172 - val_mae: 50302.1172
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 49736.6875 - mae: 49736.6875 - val_loss: 50287.6367 - val_mae: 50287.6367
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 49724.7266 - mae: 49724.7266 - val_loss: 50285.0352 - val_mae: 50285.0352
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 49710.0000 - mae: 49710.0000 - val_loss: 50281.5312 - val_mae: 50281.5312
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 49697.4297 - mae: 49697.4297 - val_loss: 50272.7695 - val_mae: 50272.7695
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 49685.5547 - mae: 49685.5547 - val_loss: 50271.2617 - val_mae: 50271.2617
Epoch 39/100
250/250 [==============================] - 0s 2ms/step - loss: 49676.6289 - mae: 49676.6289 - val_loss: 50273.6094 - val_mae: 50273.6094
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 49668.2344 - mae: 49668.2344 - val_loss: 50269.2148 - val_mae: 50269.2148
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 49653.3203 - mae: 49653.3203 - val_loss: 50262.0391 - val_mae: 50262.0391
Epoch 42/100
250/250 [==============================] - 0s 2ms/step - loss: 49643.8242 - mae: 49643.8242 - val_loss: 50244.8242 - val_mae: 50244.8242
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 49635.3984 - mae: 49635.3984 - val_loss: 50241.6914 - val_mae: 50241.6914
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 49624.5391 - mae: 49624.5391 - val_loss: 50254.0938 - val_mae: 50254.0938
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 49615.9805 - mae: 49615.9805 - val_loss: 50253.5703 - val_mae: 50253.5703
Epoch 46/100
250/250 [==============================] - 0s 2ms/step - loss: 49605.1055 - mae: 49605.1055 - val_loss: 50249.6641 - val_mae: 50249.6641
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 49597.9492 - mae: 49597.9492 - val_loss: 50243.9336 - val_mae: 50243.9336
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49591.5586 - mae: 49591.5586 - val_loss: 50241.7109 - val_mae: 50241.7109
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 49581.3125 - mae: 49581.3125 - val_loss: 50234.8164 - val_mae: 50234.8164
Epoch 50/100
250/250 [==============================] - 0s 2ms/step - loss: 49571.5078 - mae: 49571.5078 - val_loss: 50227.6250 - val_mae: 50227.6250
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 49564.9453 - mae: 49564.9453 - val_loss: 50232.1328 - val_mae: 50232.1328
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 49557.7617 - mae: 49557.7617 - val_loss: 50223.2031 - val_mae: 50223.2031
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 49550.9688 - mae: 49550.9688 - val_loss: 50236.7070 - val_mae: 50236.7070
Epoch 54/100
250/250 [==============================] - 0s 2ms/step - loss: 49543.4219 - mae: 49543.4219 - val_loss: 50232.9805 - val_mae: 50232.9805
Epoch 55/100
250/250 [==============================] - 0s 2ms/step - loss: 49538.8906 - mae: 49538.8906 - val_loss: 50227.8672 - val_mae: 50227.8672
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 49531.6328 - mae: 49531.6328 - val_loss: 50229.4375 - val_mae: 50229.4375
Epoch 57/100
250/250 [==============================] - 0s 2ms/step - loss: 49523.6758 - mae: 49523.6758 - val_loss: 50220.8516 - val_mae: 50220.8516
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 49520.4297 - mae: 49520.4297 - val_loss: 50225.9453 - val_mae: 50225.9453
Epoch 59/100
250/250 [==============================] - 0s 2ms/step - loss: 49513.7891 - mae: 49513.7891 - val_loss: 50228.7109 - val_mae: 50228.7109
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 49508.2422 - mae: 49508.2422 - val_loss: 50233.1055 - val_mae: 50233.1055
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 49503.3281 - mae: 49503.3281 - val_loss: 50228.1797 - val_mae: 50228.1797
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 49497.8906 - mae: 49497.8906 - val_loss: 50226.1641 - val_mae: 50226.1641
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 49493.4258 - mae: 49493.4258 - val_loss: 50227.1836 - val_mae: 50227.1836
Epoch 64/100
250/250 [==============================] - 0s 2ms/step - loss: 49485.5977 - mae: 49485.5977 - val_loss: 50238.4414 - val_mae: 50238.4414
Epoch 65/100
250/250 [==============================] - 0s 2ms/step - loss: 49480.2148 - mae: 49480.2148 - val_loss: 50239.1602 - val_mae: 50239.1602
Epoch 66/100
250/250 [==============================] - 0s 2ms/step - loss: 49475.0469 - mae: 49475.0469 - val_loss: 50229.2070 - val_mae: 50229.2070
Epoch 67/100
250/250 [==============================] - 0s 2ms/step - loss: 49472.9609 - mae: 49472.9609 - val_loss: 50230.9570 - val_mae: 50230.9570

In [23]:
%load_ext tensorboard

In [26]:
### Evaluate model on the test data
test_loss,test_mae = model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 931us/step - loss: 50220.8516 - mae: 50220.8516
Test MAE : 50220.8515625

In [27]:
model.save('regression_model.h5')

d:\ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(